env:
  - DOCKER_COMPOSE_VERSION=1.4.2
os: 
  - linux
arch: 
  - arm64
  - amd64
dist: bionic
services: 
  - docker

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: INFRA-243
