env:
  - DOCKER_COMPOSE_VERSION=1.4.2
os: 
  - linux
arch: 
  - arm64
  - amd64
dist: bionic
services: 
  - docker

before_install:
  - docker-compose -p $TRAVIS_COMMIT build

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: INFRA-243
